services:
  codex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codex-playground
    ports:
      - "80:80"
    restart: unless-stopped
    # Optional: if you use environment variables
    # env_file:
    #   - .env
