name: codex-1 → main

on:
  push:
    branches:
      - codex-1

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if PAT_TOKEN is set
        run: |
          if [ -z "${GH_TOKEN}" ]; then
            echo "❌ PAT_TOKEN is not set!"
            exit 1
          else
            echo "✅ PAT_TOKEN is set."
          fi
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Check if PR already exists
        id: check_pr
        run: |
          if gh pr view --base main --head codex-1 > /dev/null 2>&1; then
            echo "PR already exists"
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "No existing PR found"
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create PR using GitHub CLI
        if: steps.check_pr.outputs.exists == 'false'
        run: |
          gh pr create \
            --title "codex-1 → main" \
            --body "This PR was auto-generated after a push to codex-1." \
            --base main \
            --head codex-1 \
            --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
