name: Auto PR to main from codex-1

on:
  pull_request:
    branches:
      - codex-1
    types:
      - closed

jobs:
  create-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: codex-1
          title: "Auto PR: codex-1 → main"
          body: |
            This pull request was automatically created after a PR was merged into `codex-1`.
            Please review and merge to sync changes into `main`.
